Action

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -3,14 +3,14 @@ name: Awesome Lint Check
 on:
   push:
     paths:
-      - '**.md'
+      - '**/*.md'
   workflow_dispatch:
 
 jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
+      - name: Checkout repository
         uses: actions/checkout@v3
 
       - name: Install awesome-lint
@@ -18,14 +18,14 @@ jobs:
 
       - name: Run awesome-lint
         run: |
-          npx awesome-lint . > output.log 2>&1 || true
+          awesome-lint . > output.log 2>&1 || true
           cat output.log
 
       - name: Check for success message
         run: |
           if grep -q "✔ Linting" output.log; then
-            echo "Awesome lint passed ✅"
+            echo "✅ Awesome lint passed!"
           else
-            echo "Awesome lint failed ❌"
+            echo "❌ Awesome lint failed!"
             exit 1
           fi
